services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_restaurante
    ports:
      - "3306:3306"
    volumes:
      - ./banco_restaurante.sql:/docker-entrypoint-initdb.d/banco_restaurante.sql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app